# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Base image
  config.vm.box = "wheezy_64"
  # Hostname 
  config.vm.hostname = "test-box-s1"

  # Private network
  config.vm.network "private_network", ip: "192.168.33.14"

  # Provider overide
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  # Provisioning
  config.vm.provision "puppet" do |puppet|
    puppet.manifest_file = "base.pp"
    puppet.module_path = "modules"
    puppet.options = "--verbose --debug"
  end
end

